services:
  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vaulttoken123

  pki-setup:
    image: hashicorp/vault:latest
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: vaulttoken123
    volumes:
      - ./container-setup-scripts/pki-setup.sh:/pki-setup.sh:ro
      - pki:/pki
    command: sh /pki-setup.sh

  broker:
    image: samply/beam-broker:main
    depends_on:
      pki-setup:
        condition: service_completed_successfully
    environment:
      BROKER_URL: http://broker:8080
      PKI_ADDRESS: http://vault:8200
      PKI_APIKEY_FILE: /pki/pki.secret
      ROOTCERT_FILE: /pki/root.crt.pem
    volumes:
      - pki:/pki:ro

  central-proxy:
    image: samply/beam-proxy:main
    depends_on:
      - broker
    environment:
      BROKER_URL: http://broker:8080
      PROXY_ID: central-proxy.broker
      APP_central_KEY: centralkey123
      PRIVKEY_FILE: /pki/central-proxy.priv.pem
      ROOTCERT_FILE: /pki/root.crt.pem
    volumes:
      - pki:/pki:ro

  central:
    build:
      context: ../
      dockerfile: Dockerfile.central
    depends_on:
      - central-proxy
    environment:
      - BEAM_URL=http://central-proxy:8081
      - BEAM_ID=central.central-proxy.broker
      - BEAM_SECRET=centralkey123
      - verbis_GITLAB_URL=https://git.verbis.dkfz.de
      - verbis_GITLAB_REPO_FORMAT=bridgehead-configurations/bridgehead-config-#
      - verbis_GITLAB_API_ACCESS_TOKEN=${GITLAB_API_ACCESS_TOKEN}

  # This container contains both a beam proxy and the secret sync local component
  local:
    build:
      context: ../
      dockerfile: Dockerfile.local
    depends_on:
      - central
    environment:
      - PROXY_ID=dev-tim.broker
      - GITLAB_PROJECT_ACCESS_TOKEN_PROVIDER=central.central-proxy.broker
      - PRIVKEY_FILE=/pki/dev-tim.priv.pem
      - ROOTCERT_FILE=/pki/root.crt.pem
      - BROKER_URL=http://broker:8080
      - SECRET_DEFINITIONS=GitLabProjectAccessToken:GIT_CONFIG_REPO_TOKEN:verbis
      - CACHE_PATH=/usr/local/cache/cache.txt
    volumes:
      - ./cache:/usr/local/cache
      - pki:/pki:ro

volumes:
  pki: